using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PCL.Core.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class ArgumentsHandlersGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerClassProvider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => _GetArgumentHandlers(ctx))
            .Where(static x => x is not null);
        
        var handlersProvider = handlerClassProvider.Collect();
        
        context.RegisterSourceOutput(handlersProvider, _Generate);
    }
    
    private static string? _GetArgumentHandlers(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        
        var handlerAttribute = classDeclaration.AttributeLists
            .SelectMany(al => al.Attributes)
            .FirstOrDefault(a => a.Name.ToString().Contains("ArgumentHandler"));
        
        if (handlerAttribute == null) return null;
        
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        return symbol?.ToDisplayString();
    }

    private static void _Generate(SourceProductionContext context, ImmutableArray<string?> handlerClasses)
    {
        if (handlerClasses == null) return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// 此文件由 Source Generator 自动生成，请勿手动修改");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine("namespace PCL.Core.App.Arguments;");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class ArgumentsService");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly List<IArgumentHandler> _handlers = [];");
        builder.AppendLine();
        builder.AppendLine("    private void _InitializeHandlers()");
        builder.AppendLine("    {");
        foreach (var handlerClass in handlerClasses.Where(h => h != null))
        {
            builder.AppendLine($"        _handlers.Add(new {handlerClass}");
            builder.AppendLine("        {");
            builder.AppendLine("            ParentContext = Context");
            builder.AppendLine("        });");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        context.AddSource("ArgumentsService.g.cs", builder.ToString());
    }
}