name: Build Test

on:
  push:
    branches:
      - main
    paths:
      - "*/**"
      - "PCL.Core.csproj"
  pull_request:
    branches:
      - main
    paths:
      - "*/**"
      - "PCL.Core.csproj"
  workflow_dispatch: 

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - configuration: Debug
            architecture: x64
          - configuration: Debug
            architecture: ARM64
      fail-fast: true
    uses: ./.github/workflows/reusable_build.yml
    with:
      configuration: ${{ matrix.configuration }}
      architecture: ${{ matrix.architecture }}
    secrets: inherit

  qodana:
    name: Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      # 预先构建项目并生成源代码
      - name: Pre-build with Source Generators
        run: |
          # 恢复依赖
          dotnet restore PCL.Core.csproj
          
          # 构建项目并输出生成的源代码
          dotnet build PCL.Core.csproj \
            -c Debug \
            -p:Platform=x64 \
            -p:EmitCompilerGeneratedFiles=true \
            -p:CompilerGeneratedFilesOutputPath=./generated
          
          # 列出生成的文件（用于调试）
          echo "Generated files:"
          find ./generated -name "*.cs" -type f | head -20
          
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args:
            --linter, qodana-dotnet, --within-docker, false
          use-annotations: true