name: Code Quality
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  qodana:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Prepare Project
        run: |
          msbuild "PCL.Core.csproj" /t:Restore /t:GenerateLifecycleServiceTypes

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.1
        with:
          args: --ide,QDNET
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
